### ISSUE TITLE
Problem about  pip install -r requirements.txt . Could not find PromptCoder

### ISSUE THREAD

**Issue by ppzhr** [agiresearch/WarAgent#2]
/WarAgent$ pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement PromptCoder (from versions: none)
ERROR: No matching distribution found for PromptCoder

**Comment by ppzhr** [comment]
we also could not find re

**Comment by Wenyueh** [comment]
Hello, 

Please using the following to install promptcoder:

git clone https://github.com/dhh1995/PromptCoder
cd PromptCoder
pip install -e .


I've updated the requirement.txt
