### ISSUE TITLE
please re-examine your code

### ISSUE THREAD

**Issue by xiaoxuanNLP** [agiresearch/WarAgent#3]
Terrible code. The requirements.txt file fails to specify the minimal environmental dependencies, and there's incorrect package naming (for example, 'regex' is written as 're'). There's even an instance in history_setting/agent_profile_WWII.py where a string isn't enclosed in double quotes (line 221).

Please, please re-examine your code—it's seriously terrible.

**Comment by Wenyueh** [comment]
Hello, thank you for catching the problems. It was caused when migrating the code from my private repo to this repo.

I've updated the requirements.txt as well as WWII
