### ISSUE TITLE
Can not install ast，Could you please double check your requirements? Thank you！

### ISSUE THREAD

**Issue by ppzhr** [agiresearch/WarAgent#4]
Hello, I found that while installing requirements, I cannot install ast according to the configuration you provided. The error message is as follows:
Collecting ast
  Using cached AST-0.0.2.tar.gz (19 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-w7d_sxvz/ast_9ecbc85df5ad40d58e955c5b08e60df9/setup.py", line 6, in <module>
          README = codecs.open(os.path.join(here, 'AST/README'), encoding='utf8').read()
        File "/home/zhr/anaconda3/envs/waragent/lib/python3.9/codecs.py", line 905, in open
          file = builtins.open(filename, mode, buffering)
      FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-w7d_sxvz/ast_9ecbc85df5ad40d58e955c5b08e60df9/AST/README'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

#===========================================================

I tried changing the Python version and updating the pip，But none of this is useful.
File prompted in error message: ”FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-w7d_sxvz/ast_9ecbc85df5ad40d58e955c5b08e60df9/AST/README'“Unable to find

**Comment by Wenyueh** [comment]
Sorry.
requirements.txt modified.
