### ISSUE TITLE
Missing files and dependencies

### ISSUE THREAD

**Issue by ppzhr** [agiresearch/WarAgent#5]
Hello, it seems that your code is still missing files and dependencies. Could you please send out the complete code? I really want to use your agent, thank you!

(waragent) zhr@zhr-virtual-machine:~/war/WarAgent-main/src$ python main.py --model 'your model choice: {gpt-4}' --scenario WWI --present_thought_process
Traceback (most recent call last):
  File "/home/zhr/war/WarAgent-main/src/main.py", line 24, in <module>
    from history_setting.action_definition import *
  File "/home/zhr/war/WarAgent-main/src/history_setting/action_definition.py", line 24, in <module>
    from procoder.functional import format_prompt, replaced_submodule
ModuleNotFoundError: No module named 'procoder'

**Comment by Wenyueh** [comment]
Hello, the procoder is from https://github.com/dhh1995/PromptCoder. 
Please follow the install environment section in README to download this dependency. This package is unfortunately not available by pip install, and you have to download it from the source code.
Let me know if it works.

**Comment by ppzhr** [comment]
I added PromptCoder to the project, but there are still missing dependencies。Could you please modify requirements. txt and compile a complete version of the dependency list?

Traceback (most recent call last):
  File "/home/zhr/war/WarAgent-main/src/main.py", line 29, in <module>
    from building_blocks.agent import *
  File "/home/zhr/war/WarAgent-main/src/building_blocks/agent.py", line 36, in <module>
    from building_blocks.board import Board
  File "/home/zhr/war/WarAgent-main/src/building_blocks/board.py", line 25, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'

**Comment by Wenyueh** [comment]
ok done, add networkx, scikit-learn, matplotlib

**Comment by Wenyueh** [comment]
I will close the issue if it works for you now

**Comment by ppzhr** [comment]
Hello, my temporary question is how to enable the server to access the GPT4 API through a proxy. I am a student studying in China, so I have this question. Thank you very much for your answer.

**Comment by Wenyueh** [comment]
Hi, I will close the issue. Please create a different issue for this problem.
Unfortunately, I am not familiar with using GPT4 through proxy. You can create a new issue and see if anybody knows. But I think if you can use GPT4 proxy to obtain output, you can do the same here by directly replacing the openai client in the run_gpt function in the file building_blocks/model.py
