### ISSUE TITLE
hi, bro, I thought it were not even a so-called issue, but I'm of magnificent curiosity that "Where's your alienAgent"...

### ISSUE THREAD

**Issue by Konisberg** [agiresearch/WarAgent#8]
btw, are you also convinced that AGI will come soon;
And the most importantly, regardless of whether this is true, one will still commit wholeheartedly to the pursuit of AGI.
I've got lots of passions and motivations when I find it seems still many guys who has been devoted to AGI even before ChatGPT came out.

**Comment by agiresearch** [comment]
Thank you for the inspiring discussion. When and how to achieve AGI is still an ongoing pursuit for the community. We tend to believe that AGI will not be achieved by a single model, but will be a system, which should be scalable and extendable enough to host a diverse and increasing amount of skills. Of course, as you mentioned, and we totally agree--that although people may hold different philosophies and theories towards AGI, a wholehearted pursuit to this dream is a shared goal for our community.
